layout_spectrum: 0.396248
typography_spectrum: 0.46722
color:
  saturation: 0.9770309
  lightness: 0.4897141
  brandStrength: 0.5055298
  rhythmicContrast: 0.6372657
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
name: Ecka
